dotenv: .env
networks:
  mumbai_moralis:
    verify: False
  kovan:
    verify: True
  mainnet:
    verify: False
wallets:
  from_blue_key: ${WALLET_PRIVATE_KEY_BLUE}
  from_green_key: ${WALLET_PRIVATE_KEY_GREEN}
